// AUTO-GENERATED by scripts/generate-og-data.ts, do not edit manually.
// regenerated on every build via `pnpm run build`.

export const BLOG_POSTS = [
  {
    "id": "internet-useless-info",
    "title": "THE INTERNET IS MAKING ME ODDLY GOOD AT KNOWING RANDOM USELESS THINGS",
    "snippet": "how random yt videos and bullshit geography studying can quite literally build a highway of hyper specific trivia",
    "link": "internet-useless-info",
    "date": "Sep 20, 2026",
    "category": "reflecting"
  },
  {
    "id": "2slimey-changed-how-i-listen",
    "title": "2slimey changed the way I listen to music.",
    "snippet": "Yes, a genuine opinion of mine. If this title made you roll your eyes, you are exactly who this is for! :)",
    "link": "2slimey-changed-how-i-listen",
    "date": "Aug 12, 2026",
    "category": "music"
  },
  {
    "id": "more-old-blogs-restored",
    "title": "even more history! part 2 of restoring the early blogs",
    "snippet": "restored a few more gems from the early 2026 snapshots, including some of my favorite rants and the revamped markdown stress test.",
    "link": "more-old-blogs-restored",
    "date": "Jul 7, 2026",
    "category": "update"
  },
  {
    "id": "markdown-test",
    "title": "markdown stress test, testing the parser",
    "snippet": "checking if the new react-markdown setup can handle me.",
    "link": "markdown-test",
    "date": "Jul 7, 2026",
    "category": "devlog"
  },
  {
    "id": "return-of-the-old-blogs",
    "title": "the old blogs are back. all of them.",
    "snippet": "i dug up every old post from the old stabbed.wtf, going all the way back to the very beginning of the \"project inception\". they're all here again now, preserved exactly as they were back when i wrote them.",
    "link": "return-of-the-old-blogs",
    "date": "Jul 6, 2026",
    "category": "update"
  },
  {
    "id": "stop-moving-my-screen",
    "title": "stop moving my screen! this is why modern web design is a motion sickness hazard...",
    "snippet": "let's talk about how modern web designers went insane with motion, and why i finally finished my global toggle to turn off the damned thing!",
    "link": "stop-moving-my-screen",
    "date": "Jul 5, 2026",
    "category": "dev"
  },
  {
    "id": "leaving-vercel",
    "title": "leaving vercel; migrating my project to cloudflare!",
    "snippet": "here is why i finally dropped vercel's proprietary ecosystem, swapped to cloudflare pages, and built my own localized deployment helper.",
    "link": "leaving-vercel",
    "date": "May 25, 2026",
    "category": "cybersec"
  },
  {
    "id": "data-sovereignty",
    "title": "Why i refuse to trust the majority of the cloud..",
    "snippet": "Hoarding data is a radical act of self-preservation in a world of corporate greed tech giants.",
    "link": "data-sovereignty",
    "date": "May 24, 2026",
    "category": "research"
  },
  {
    "id": "bladeandbath-shitpost",
    "title": "brutal fantasies is literally the peak of human existence",
    "snippet": "ok.. i'm coming back from the dead again to talk about the only album that matters right now, and i know its late talking about it. sorry not sorry.",
    "link": "bladeandbathpeak",
    "date": "Apr 30, 2026",
    "category": "music"
  },
  {
    "id": "ricing-supremacy",
    "title": "ricing supremacy and why ricing makes you an actually better dev",
    "snippet": "PLEASE stop staring at ugly default themes. your environment is a reflection of your work.",
    "link": "ewaste-supremacy",
    "date": "Apr 26, 2026",
    "category": "tech"
  },
  {
    "id": "idek-anymore",
    "title": "turning ewaste into a small dev rig",
    "snippet": "this is why I decided to torture myself by putting debian on a snappy chromebook and how it actually kinda works!",
    "link": "ewaste-1-fr",
    "date": "Mar 15, 2026",
    "category": "linux"
  },
  {
    "id": "more-hardware-updates-feb-2026",
    "title": "mobile magic & hardware redesign",
    "snippet": "the new mobile \"more\" menu and the revamped hardware section.",
    "link": "more-hardware-updates-feb-2026",
    "date": "Feb 11, 2026",
    "category": "devlog"
  },
  {
    "id": "site-overhaul-feb-2026",
    "title": "de-sanitizing the site",
    "snippet": "a deep dive into why i gutted the old design, added new tweaks, and gave you keys to customization.",
    "link": "feb-11-update",
    "date": "Feb 11, 2026",
    "category": "devlog"
  },
  {
    "id": "search-is-mid",
    "title": "this is why search bars are e-waste",
    "snippet": "let's be honest.. if you needed a search bar to find content on a site, you are trying too hard.",
    "link": "search-is-mid",
    "date": "Feb 10, 2026",
    "category": "opinions"
  },
  {
    "id": "unw-upw-is-a-bible-lol",
    "title": "my networking wiki just got a full reinstallation",
    "snippet": "after a whole year of rotting, the wiki is finally a 300k character monster.",
    "link": "unw-upw-is-a-bible-lol",
    "date": "Feb 03, 2026",
    "category": "devlog"
  },
  {
    "id": "cybersec-101",
    "title": "stop making it easy to pwn you",
    "snippet": "the absolute bare minimum to not get wiped out online.",
    "link": "cybersec-101",
    "date": "Jul 07, 2026",
    "category": "cybersecurity"
  },
  {
    "id": "sysdupd",
    "title": "sysdupd: arch updates without the headache",
    "snippet": "i finally got tired of manual pacman runs, so i built a libadwaita manager for my personal use",
    "link": "sysdupd",
    "date": "Jan 16, 2026",
    "category": "dev"
  },
  {
    "id": "pixel-10-pro-honest-review",
    "title": "long term pixel 10 pro use: my review of the tensor G5",
    "snippet": "the 3nm transition, on device ai, and why the pixel 10 pro is finally a consistent daily driver.",
    "link": "pixel-10-review",
    "date": "Jan 16, 2026",
    "category": "research"
  },
  {
    "id": "cloud-is-someone-elses-computer",
    "title": "your cloud is just someone elses computer.",
    "snippet": "this is why i hoard data (and you probably should too)",
    "link": "cloud-is-someone-elses-computer",
    "date": "Jan 14, 2026",
    "category": "research"
  },
  {
    "id": "why-i-actually-use-arch",
    "title": "why I actually use arch.. (and it’s not a joke)",
    "snippet": "everyone thinks arch users just want to flex their fastfetch, but i actually just want a system that doesnt hand bs over to me...",
    "link": "why-i-actually-use-arch",
    "date": "Jan 14, 2026",
    "category": "research"
  },
  {
    "id": "the-internet-is-dead",
    "title": "the internet is dead.",
    "snippet": "if you think youre still talking to real people on big platforms, i have a bridge to sell you.",
    "link": "the-internet-is-dead",
    "date": "Jan 12, 2026",
    "category": "research"
  },
  {
    "id": "epstein-files-is-a-joke",
    "title": "the epstein \"files\" are a joke",
    "snippet": "so the DOJ finally dropped the files and... surprise! it’s basically just 50 pages of blacked out text...",
    "link": "epstein-files-is-a-joke",
    "date": "Dec 21, 2025",
    "category": "research"
  },
  {
    "id": "why-love-open-source",
    "title": "heres why i love open source - 2",
    "snippet": "honestly, open source is just better. it’s all about the community and...",
    "link": "why-love-open-source",
    "date": "Nov 12, 2025",
    "category": "dev"
  },
  {
    "id": "my-take-on-ai",
    "title": "My take on ai",
    "snippet": "My take on ai; ai is a companion, not a replacement. an assistant, and nothing more",
    "link": "my-take-on-ai",
    "date": "Nov 16, 2025",
    "category": "ai"
  },
  {
    "id": "keeping-it-live",
    "title": "The VIREX portfolio is UPDATED",
    "snippet": "I've completely revamped and fixed + polished the code on ALL pages",
    "link": "keeping-it-live",
    "date": "Nov 16, 2025",
    "category": "dev"
  },
  {
    "id": "project-update-2025-11-12",
    "title": "Project Update 2025-11-12",
    "snippet": "Major fixes and improvements across the site.",
    "link": "project-update-2025-11-12",
    "date": "Nov 12, 2025",
    "category": "dev"
  },
  {
    "id": "project-update-2025-11-08",
    "title": "Project Update 2025-11-08",
    "snippet": "Updated multiple things on the site for better UX...",
    "link": "project-update-2025-11-08",
    "date": "Nov 8, 2025",
    "category": "dev"
  },
  {
    "id": "ah-shi-here-we-go-again",
    "title": "Ah shi, here we go again.",
    "snippet": "Rockstar has JUST announced that GTA 6 will be delayed to November 19th, 2026",
    "link": "ah-shi-here-we-go-again",
    "date": "Nov 6, 2025",
    "category": "gaming"
  },
  {
    "id": "future-plans-and-goals",
    "title": "Future Plans and Goals",
    "snippet": "I'm really looking forward to new projects and even more learning opportunities",
    "link": "future-plans-and-goals",
    "date": "Nov 7, 2025",
    "category": "goals"
  },
  {
    "id": "importance-of-cybersecurity",
    "title": "The Importance of Cybersecurity, especially in Development",
    "snippet": "understanding cybersecurity is a no brainer",
    "link": "importance-of-cybersecurity",
    "date": "Nov 6, 2025",
    "category": "security"
  },
  {
    "id": "why-i-love-open-source-og",
    "title": "Why I Love Open Source",
    "snippet": "Open source software has always been so important in my development journey",
    "link": "why-i-love-open-source-og",
    "date": "Nov 5, 2025",
    "category": "dev"
  },
  {
    "id": "welcome-to-the-blog",
    "title": "Welcome to the Blog!",
    "snippet": "This is the first blog post!",
    "link": "welcome-to-the-blog",
    "date": "Nov 4, 2025",
    "category": "blog"
  },
  {
    "id": "project-update-2025-11-04",
    "title": "Project Update 2025-11-04",
    "snippet": "I've been working on a LOT of updates and features for my portfolio.",
    "link": "project-update-2025-11-04",
    "date": "Nov 4, 2025",
    "category": "dev"
  },
  {
    "id": "project-update-2025-11-03",
    "title": "Project Update 2025-11-03",
    "snippet": "Fully overhauled and recoded search wrapper & portfolio from scratch",
    "link": "project-update-2025-11-03",
    "date": "Nov 3, 2025",
    "category": "dev"
  },
  {
    "id": "project-update-2025-10-20",
    "title": "Project Update 2025-10-20",
    "snippet": "Changed fonts & added transparency/glassy effects across the site.",
    "link": "project-update-2025-10-20",
    "date": "Oct 20, 2025",
    "category": "dev"
  },
  {
    "id": "project-update-2025-10-19",
    "title": "Project Update 2025-10-19",
    "snippet": "Fixed and revamped various parts of the UI",
    "link": "project-update-2025-10-19",
    "date": "Oct 19, 2025",
    "category": "dev"
  },
  {
    "id": "project-update-2025-6-12",
    "title": "Project Inception 2025-6-12",
    "snippet": "Started with the idea of creating a Material Design testing playground as a hobby.",
    "link": "project-update-2025-6-12",
    "date": "Jun 12, 2025",
    "category": "beginning"
  }
];

export const MUSIC_RELEASES = [
  {
    "id": "HATEWARE",
    "title": "HATEWARE",
    "type": "Single",
    "description": "HATEWARE consists of three radio eq dropouts, harsh 808s, and zero breathing room. single dropped aug 13, 2026. written, produced, and mixed by rxvirex",
    "genre": "Rage/Trap",
    "releaseDate": "2026",
    "ogImage": "https://stabbed.wtf/albums/HATEWARE.png"
  },
  {
    "id": "FIRSTATTEMPT",
    "title": "FIRST ATTEMPT",
    "type": "Album",
    "description": "FIRST ATTEMPT is a debut full length release album. loud and grainy 808s, blown out distortion, seriously fucked up sound design, along with whatever else ended up in the mix. written, produced, and mixed by rxvirex (virex).",
    "genre": "Rage/Trap",
    "releaseDate": "2026",
    "ogImage": "https://stabbed.wtf/albums/FIRSTATTEMPT.png"
  }
];
