
import fs from "fs";
import path from "path";
import dotenv from "dotenv";
import { BLOG_POSTS, MUSIC_RELEASES, PROJECTS } from "../src/constants.ts";

dotenv.config();

const lastfmApiKey = process.env.LASTFM_API_KEY || process.env.VITE_LASTFM_API_KEY || "";
const lastfmUsername = process.env.LASTFM_USERNAME || process.env.VITE_LASTFM_USERNAME || "rxvirex";

const outputDir = path.join(process.cwd(), "functions", "_generated");
const outputPath = path.join(outputDir, "og-data.js");
const albumsDir = path.join(process.cwd(), "public", "albums");
const SITE_URL = "https://stabbed.wtf";

/** resolve the actual album cover URL for a release at build time. */
function resolveAlbumCoverUrl(releaseId: string, coverUrl?: string | null): string {
  // if a coverUrl is explicitly set on the release, use it directly.
  if (coverUrl) {
    return coverUrl.startsWith("http") ? coverUrl : `${SITE_URL}${coverUrl}`;
  }

  // check public/albums/<id>.<ext> in priority order.
  const exts = ["webp", "png", "jpg", "jpeg", "avif"];
  for (const ext of exts) {
    const filePath = path.join(albumsDir, `${releaseId}.${ext}`);
    if (fs.existsSync(filePath)) {
      return `${SITE_URL}/albums/${releaseId}.${ext}`;
    }
  }

  // nothing found = fall back to the default pfp image.
  return `${SITE_URL}/photography/pfp/main.png`;
}

// strip heavy content field, workers only need id, title, snippet, link, date, category.
const blogData = BLOG_POSTS.map(({ id, title, snippet, link, date, category }) => ({
  id,
  title,
  snippet,
  link,
  date,
  category,
}));

// strip heavy fields from music releases and bake in the resolved cover URL.
const musicData = MUSIC_RELEASES.map(({ id, title, type, description, genre, coverUrl, releaseDate }) => ({
  id,
  title,
  type,
  description,
  genre,
  releaseDate,
  // resolved at build time. workers use this directly, no guessing needed.
  ogImage: resolveAlbumCoverUrl(id, coverUrl),
}));

const output = `// AUTO-GENERATED by scripts/generate-og-data.ts, do not edit manually.
// regenerated on every build via \`pnpm run build\`.

export const BLOG_POSTS = ${JSON.stringify(blogData, null, 2)};

export const MUSIC_RELEASES = ${JSON.stringify(musicData, null, 2)};
`;

const terminalOutputPath = path.join(outputDir, "terminal-data.js");
const terminalOutput = `// AUTO-GENERATED by scripts/generate-og-data.ts, do not edit manually.
// regenerated on every build using \`pnpm run build\`.

export const BLOG_POSTS = ${JSON.stringify(BLOG_POSTS, null, 2)};

export const PROJECTS = ${JSON.stringify(PROJECTS || [], null, 2)};

export const MUSIC_RELEASES = ${JSON.stringify(MUSIC_RELEASES, null, 2)};

export const PROFILE = {
  name: "virex",
  alias: "rxvirex / hnpf",
  tagline: "code can be used as a form of protest :)",
  bio: "semi-fullstack dev, linux enthusiast, music prod, and open-source contributor.",
  site: "https://stabbed.wtf",
  github: "https://github.com/hnpf",
  discord: "https://discord.gg/TSZNYbjzF7",
  source: "https://github.com/hnpf/stabbed.wtf",
  rss: "https://stabbed.wtf/rss.xml",
  bandcamp: "https://rxvirex.bandcamp.com"
};

export const LASTFM_CONFIG = {
  apiKey: ${JSON.stringify(lastfmApiKey)},
  username: ${JSON.stringify(lastfmUsername)}
};
`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(outputPath, output, "utf-8");
fs.writeFileSync(terminalOutputPath, terminalOutput, "utf-8");

// log resolved covers so you can spot missing art at a glance.
console.log(`Generated OG data: ${blogData.length} blog post(s), ${musicData.length} music releases → ${outputPath}`);
console.log(`Generated Terminal data → ${terminalOutputPath}`);
for (const r of musicData) {
  console.log(`  🎵 ${r.id} → ${r.ogImage}`);
}

